services:
  eagenda.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - SQL_CONNECTION_STRING=Host=db;Port=5433;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - NEWRELIC_LICENSE_KEY=${NEWRELIC_LICENSE_KEY}
      - AUTOMAPPER_LICENSE_KEY=${AUTOMAPPER_LICENSE_KEY}
      - JWT_GENERATION_KEY=${JWT_GENERATION_KEY}
      - JWT_AUDIENCE_DOMAIN=https://localhost:5253
      - REDIS_CONNECTION_STRING=cache:6379,abortConnect=false
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  db:
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
 
  cache:
    environment:
      name: eagenda-cache
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"